apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: build-suite-test-component-image-url-ejhv
  namespace: e2e-test-apbh
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-app-wfww
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: build-suite-test-component-image-url-ejhv
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: build-suite-test-component-image-url-ejhv-
      labels:
        build.appstudio.openshift.io/application: test-app-wfww
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: build-suite-test-component-image-url-ejhv
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: e2e-test-apbh
    spec:
      params:
      - name: git-url
        value: https://github.com/redhat-appstudio-qe/devfile-sample-hello-world
      - name: output-image
        value: quay.io/psturc/test-images-protected:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: docker/Dockerfile
      - name: path-context
        value: .
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:510fa6e99f1fa1f816c96354bbaf1ad155c6d9c3
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: build-suite-test-component-image-url-ejhv/$(tt.params.git-revision)
    status: {}
status: {}
